apiVersion: v1
kind: Service
metadata:
  annotation:
    cloud.google.com/backend-config: '{"default": "my-backend-config"}'
  name: elearn-web
spec:
  selector:
    app: elearn-web
  type: NodePort
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 80
    type: TCP
    requestPath: /