apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearn-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elearn-search
  template:
    metadata:
      labels:
        app: elearn-search
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/SEARCH_IMAGE:TAG
          imagePullPolicy: Always
          env:
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: dbusername
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: dbpassword
            - name: MINIO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: minioaccesskey
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: miniosecretkey