apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearn-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elearn-search
  template:
    metadata:
      labels:
        app: elearn-search
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/SEARCH_IMAGE:TAG
          imagePullPolicy: Always